// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proxy/queqiao/config.proto

package queqiao

import (
	net "github.com/xtls/xray-core/common/net"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proxy_queqiao_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_queqiao_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proxy_queqiao_config_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Devices       []*Device              `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_queqiao_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_queqiao_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_queqiao_config_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ServerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProviderId          string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	GatewayId           string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	AllowPrivate        bool                   `protobuf:"varint,3,opt,name=allow_private,json=allowPrivate,proto3" json:"allow_private,omitempty"`
	Accounts            []*Account             `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	RootPin             string                 `protobuf:"bytes,5,opt,name=root_pin,json=rootPin,proto3" json:"root_pin,omitempty"`
	RootCertificate     string                 `protobuf:"bytes,6,opt,name=root_certificate,json=rootCertificate,proto3" json:"root_certificate,omitempty"`
	RootCertificatePath string                 `protobuf:"bytes,7,opt,name=root_certificate_path,json=rootCertificatePath,proto3" json:"root_certificate_path,omitempty"`
	Certificate         string                 `protobuf:"bytes,8,opt,name=certificate,proto3" json:"certificate,omitempty"`
	CertificatePath     string                 `protobuf:"bytes,9,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	PrivateKey          string                 `protobuf:"bytes,10,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PrivateKeyPath      string                 `protobuf:"bytes,11,opt,name=private_key_path,json=privateKeyPath,proto3" json:"private_key_path,omitempty"`
	HopPortCount        int32                  `protobuf:"varint,12,opt,name=hop_port_count,json=hopPortCount,proto3" json:"hop_port_count,omitempty"`
	Congestion          string                 `protobuf:"bytes,13,opt,name=congestion,proto3" json:"congestion,omitempty"`
	MaxSessions         int32                  `protobuf:"varint,14,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	FlowIdleTimeout     int32                  `protobuf:"varint,15,opt,name=flow_idle_timeout,json=flowIdleTimeout,proto3" json:"flow_idle_timeout,omitempty"`
	RootPrivateKey      string                 `protobuf:"bytes,16,opt,name=root_private_key,json=rootPrivateKey,proto3" json:"root_private_key,omitempty"`
	RootPrivateKeyPath  string                 `protobuf:"bytes,17,opt,name=root_private_key_path,json=rootPrivateKeyPath,proto3" json:"root_private_key_path,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_queqiao_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_queqiao_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_queqiao_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ServerConfig) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ServerConfig) GetAllowPrivate() bool {
	if x != nil {
		return x.AllowPrivate
	}
	return false
}

func (x *ServerConfig) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ServerConfig) GetRootPin() string {
	if x != nil {
		return x.RootPin
	}
	return ""
}

func (x *ServerConfig) GetRootCertificate() string {
	if x != nil {
		return x.RootCertificate
	}
	return ""
}

func (x *ServerConfig) GetRootCertificatePath() string {
	if x != nil {
		return x.RootCertificatePath
	}
	return ""
}

func (x *ServerConfig) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ServerConfig) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *ServerConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ServerConfig) GetPrivateKeyPath() string {
	if x != nil {
		return x.PrivateKeyPath
	}
	return ""
}

func (x *ServerConfig) GetHopPortCount() int32 {
	if x != nil {
		return x.HopPortCount
	}
	return 0
}

func (x *ServerConfig) GetCongestion() string {
	if x != nil {
		return x.Congestion
	}
	return ""
}

func (x *ServerConfig) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *ServerConfig) GetFlowIdleTimeout() int32 {
	if x != nil {
		return x.FlowIdleTimeout
	}
	return 0
}

func (x *ServerConfig) GetRootPrivateKey() string {
	if x != nil {
		return x.RootPrivateKey
	}
	return ""
}

func (x *ServerConfig) GetRootPrivateKeyPath() string {
	if x != nil {
		return x.RootPrivateKeyPath
	}
	return ""
}

type ClientConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Server                *net.Endpoint          `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ProviderId            string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	GatewayId             string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	AccountId             string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DeviceId              string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName            string                 `protobuf:"bytes,6,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Sni                   string                 `protobuf:"bytes,7,opt,name=sni,proto3" json:"sni,omitempty"`
	RootPin               string                 `protobuf:"bytes,8,opt,name=root_pin,json=rootPin,proto3" json:"root_pin,omitempty"`
	RootCertificate       string                 `protobuf:"bytes,9,opt,name=root_certificate,json=rootCertificate,proto3" json:"root_certificate,omitempty"`
	RootCertificatePath   string                 `protobuf:"bytes,10,opt,name=root_certificate_path,json=rootCertificatePath,proto3" json:"root_certificate_path,omitempty"`
	DeviceCertificate     string                 `protobuf:"bytes,11,opt,name=device_certificate,json=deviceCertificate,proto3" json:"device_certificate,omitempty"`
	DeviceCertificatePath string                 `protobuf:"bytes,12,opt,name=device_certificate_path,json=deviceCertificatePath,proto3" json:"device_certificate_path,omitempty"`
	DevicePrivateKey      string                 `protobuf:"bytes,13,opt,name=device_private_key,json=devicePrivateKey,proto3" json:"device_private_key,omitempty"`
	DevicePrivateKeyPath  string                 `protobuf:"bytes,14,opt,name=device_private_key_path,json=devicePrivateKeyPath,proto3" json:"device_private_key_path,omitempty"`
	HopPortCount          int32                  `protobuf:"varint,15,opt,name=hop_port_count,json=hopPortCount,proto3" json:"hop_port_count,omitempty"`
	CongestionController  string                 `protobuf:"bytes,16,opt,name=congestion_controller,json=congestionController,proto3" json:"congestion_controller,omitempty"`
	QuicPool              bool                   `protobuf:"varint,17,opt,name=quic_pool,json=quicPool,proto3" json:"quic_pool,omitempty"`
	WaitForOpenAck        bool                   `protobuf:"varint,18,opt,name=wait_for_open_ack,json=waitForOpenAck,proto3" json:"wait_for_open_ack,omitempty"`
	UdpOverStream         bool                   `protobuf:"varint,19,opt,name=udp_over_stream,json=udpOverStream,proto3" json:"udp_over_stream,omitempty"`
	TcpFallbackLanes      int32                  `protobuf:"varint,20,opt,name=tcp_fallback_lanes,json=tcpFallbackLanes,proto3" json:"tcp_fallback_lanes,omitempty"`
	HandshakeTimeout      int32                  `protobuf:"varint,21,opt,name=handshake_timeout,json=handshakeTimeout,proto3" json:"handshake_timeout,omitempty"`
	FlowIdleTimeout       int32                  `protobuf:"varint,22,opt,name=flow_idle_timeout,json=flowIdleTimeout,proto3" json:"flow_idle_timeout,omitempty"`
	MaxSessions           int32                  `protobuf:"varint,23,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	ChunkSize             int32                  `protobuf:"varint,24,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Transport             string                 `protobuf:"bytes,25,opt,name=transport,proto3" json:"transport,omitempty"` // "auto", "quic", or "tcp"
	FallbackDelay         int32                  `protobuf:"varint,26,opt,name=fallback_delay,json=fallbackDelay,proto3" json:"fallback_delay,omitempty"`
	FallbackGrace         int32                  `protobuf:"varint,27,opt,name=fallback_grace,json=fallbackGrace,proto3" json:"fallback_grace,omitempty"`
	UdpCooldown           int32                  `protobuf:"varint,28,opt,name=udp_cooldown,json=udpCooldown,proto3" json:"udp_cooldown,omitempty"`
	UdpFailureThreshold   int32                  `protobuf:"varint,29,opt,name=udp_failure_threshold,json=udpFailureThreshold,proto3" json:"udp_failure_threshold,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_queqiao_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_queqiao_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_queqiao_config_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConfig) GetServer() *net.Endpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ClientConfig) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ClientConfig) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ClientConfig) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ClientConfig) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ClientConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ClientConfig) GetRootPin() string {
	if x != nil {
		return x.RootPin
	}
	return ""
}

func (x *ClientConfig) GetRootCertificate() string {
	if x != nil {
		return x.RootCertificate
	}
	return ""
}

func (x *ClientConfig) GetRootCertificatePath() string {
	if x != nil {
		return x.RootCertificatePath
	}
	return ""
}

func (x *ClientConfig) GetDeviceCertificate() string {
	if x != nil {
		return x.DeviceCertificate
	}
	return ""
}

func (x *ClientConfig) GetDeviceCertificatePath() string {
	if x != nil {
		return x.DeviceCertificatePath
	}
	return ""
}

func (x *ClientConfig) GetDevicePrivateKey() string {
	if x != nil {
		return x.DevicePrivateKey
	}
	return ""
}

func (x *ClientConfig) GetDevicePrivateKeyPath() string {
	if x != nil {
		return x.DevicePrivateKeyPath
	}
	return ""
}

func (x *ClientConfig) GetHopPortCount() int32 {
	if x != nil {
		return x.HopPortCount
	}
	return 0
}

func (x *ClientConfig) GetCongestionController() string {
	if x != nil {
		return x.CongestionController
	}
	return ""
}

func (x *ClientConfig) GetQuicPool() bool {
	if x != nil {
		return x.QuicPool
	}
	return false
}

func (x *ClientConfig) GetWaitForOpenAck() bool {
	if x != nil {
		return x.WaitForOpenAck
	}
	return false
}

func (x *ClientConfig) GetUdpOverStream() bool {
	if x != nil {
		return x.UdpOverStream
	}
	return false
}

func (x *ClientConfig) GetTcpFallbackLanes() int32 {
	if x != nil {
		return x.TcpFallbackLanes
	}
	return 0
}

func (x *ClientConfig) GetHandshakeTimeout() int32 {
	if x != nil {
		return x.HandshakeTimeout
	}
	return 0
}

func (x *ClientConfig) GetFlowIdleTimeout() int32 {
	if x != nil {
		return x.FlowIdleTimeout
	}
	return 0
}

func (x *ClientConfig) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *ClientConfig) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ClientConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ClientConfig) GetFallbackDelay() int32 {
	if x != nil {
		return x.FallbackDelay
	}
	return 0
}

func (x *ClientConfig) GetFallbackGrace() int32 {
	if x != nil {
		return x.FallbackGrace
	}
	return 0
}

func (x *ClientConfig) GetUdpCooldown() int32 {
	if x != nil {
		return x.UdpCooldown
	}
	return 0
}

func (x *ClientConfig) GetUdpFailureThreshold() int32 {
	if x != nil {
		return x.UdpFailureThreshold
	}
	return 0
}

type TransportConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HopPortCount        int32                  `protobuf:"varint,1,opt,name=hop_port_count,json=hopPortCount,proto3" json:"hop_port_count,omitempty"`
	Congestion          string                 `protobuf:"bytes,2,opt,name=congestion,proto3" json:"congestion,omitempty"`
	ChunkSize           int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	QuicPool            bool                   `protobuf:"varint,4,opt,name=quic_pool,json=quicPool,proto3" json:"quic_pool,omitempty"`
	WaitForOpenAck      bool                   `protobuf:"varint,5,opt,name=wait_for_open_ack,json=waitForOpenAck,proto3" json:"wait_for_open_ack,omitempty"`
	UdpOverStream       bool                   `protobuf:"varint,6,opt,name=udp_over_stream,json=udpOverStream,proto3" json:"udp_over_stream,omitempty"`
	HandshakeTimeout    int32                  `protobuf:"varint,7,opt,name=handshake_timeout,json=handshakeTimeout,proto3" json:"handshake_timeout,omitempty"`
	FlowIdleTimeout     int32                  `protobuf:"varint,8,opt,name=flow_idle_timeout,json=flowIdleTimeout,proto3" json:"flow_idle_timeout,omitempty"`
	MaxSessions         int32                  `protobuf:"varint,9,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	TcpFallbackLanes    int32                  `protobuf:"varint,10,opt,name=tcp_fallback_lanes,json=tcpFallbackLanes,proto3" json:"tcp_fallback_lanes,omitempty"`
	Transport           string                 `protobuf:"bytes,11,opt,name=transport,proto3" json:"transport,omitempty"`
	FallbackDelay       int32                  `protobuf:"varint,12,opt,name=fallback_delay,json=fallbackDelay,proto3" json:"fallback_delay,omitempty"`
	FallbackGrace       int32                  `protobuf:"varint,13,opt,name=fallback_grace,json=fallbackGrace,proto3" json:"fallback_grace,omitempty"`
	UdpCooldown         int32                  `protobuf:"varint,14,opt,name=udp_cooldown,json=udpCooldown,proto3" json:"udp_cooldown,omitempty"`
	UdpFailureThreshold int32                  `protobuf:"varint,15,opt,name=udp_failure_threshold,json=udpFailureThreshold,proto3" json:"udp_failure_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransportConfig) Reset() {
	*x = TransportConfig{}
	mi := &file_proxy_queqiao_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportConfig) ProtoMessage() {}

func (x *TransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_queqiao_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportConfig.ProtoReflect.Descriptor instead.
func (*TransportConfig) Descriptor() ([]byte, []int) {
	return file_proxy_queqiao_config_proto_rawDescGZIP(), []int{4}
}

func (x *TransportConfig) GetHopPortCount() int32 {
	if x != nil {
		return x.HopPortCount
	}
	return 0
}

func (x *TransportConfig) GetCongestion() string {
	if x != nil {
		return x.Congestion
	}
	return ""
}

func (x *TransportConfig) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *TransportConfig) GetQuicPool() bool {
	if x != nil {
		return x.QuicPool
	}
	return false
}

func (x *TransportConfig) GetWaitForOpenAck() bool {
	if x != nil {
		return x.WaitForOpenAck
	}
	return false
}

func (x *TransportConfig) GetUdpOverStream() bool {
	if x != nil {
		return x.UdpOverStream
	}
	return false
}

func (x *TransportConfig) GetHandshakeTimeout() int32 {
	if x != nil {
		return x.HandshakeTimeout
	}
	return 0
}

func (x *TransportConfig) GetFlowIdleTimeout() int32 {
	if x != nil {
		return x.FlowIdleTimeout
	}
	return 0
}

func (x *TransportConfig) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *TransportConfig) GetTcpFallbackLanes() int32 {
	if x != nil {
		return x.TcpFallbackLanes
	}
	return 0
}

func (x *TransportConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *TransportConfig) GetFallbackDelay() int32 {
	if x != nil {
		return x.FallbackDelay
	}
	return 0
}

func (x *TransportConfig) GetFallbackGrace() int32 {
	if x != nil {
		return x.FallbackGrace
	}
	return 0
}

func (x *TransportConfig) GetUdpCooldown() int32 {
	if x != nil {
		return x.UdpCooldown
	}
	return 0
}

func (x *TransportConfig) GetUdpFailureThreshold() int32 {
	if x != nil {
		return x.UdpFailureThreshold
	}
	return 0
}

var File_proxy_queqiao_config_proto protoreflect.FileDescriptor

const file_proxy_queqiao_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/queqiao/config.proto\x12\x12xray.proxy.queqiao\x1a\x1ccommon/net/destination.proto\"D\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"^\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x124\n" +
	"\adevices\x18\x02 \x03(\v2\x1a.xray.proxy.queqiao.DeviceR\adevices\"\xb0\x05\n" +
	"\fServerConfig\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12#\n" +
	"\rallow_private\x18\x03 \x01(\bR\fallowPrivate\x127\n" +
	"\baccounts\x18\x04 \x03(\v2\x1b.xray.proxy.queqiao.AccountR\baccounts\x12\x19\n" +
	"\broot_pin\x18\x05 \x01(\tR\arootPin\x12)\n" +
	"\x10root_certificate\x18\x06 \x01(\tR\x0frootCertificate\x122\n" +
	"\x15root_certificate_path\x18\a \x01(\tR\x13rootCertificatePath\x12 \n" +
	"\vcertificate\x18\b \x01(\tR\vcertificate\x12)\n" +
	"\x10certificate_path\x18\t \x01(\tR\x0fcertificatePath\x12\x1f\n" +
	"\vprivate_key\x18\n" +
	" \x01(\tR\n" +
	"privateKey\x12(\n" +
	"\x10private_key_path\x18\v \x01(\tR\x0eprivateKeyPath\x12$\n" +
	"\x0ehop_port_count\x18\f \x01(\x05R\fhopPortCount\x12\x1e\n" +
	"\n" +
	"congestion\x18\r \x01(\tR\n" +
	"congestion\x12!\n" +
	"\fmax_sessions\x18\x0e \x01(\x05R\vmaxSessions\x12*\n" +
	"\x11flow_idle_timeout\x18\x0f \x01(\x05R\x0fflowIdleTimeout\x12(\n" +
	"\x10root_private_key\x18\x10 \x01(\tR\x0erootPrivateKey\x121\n" +
	"\x15root_private_key_path\x18\x11 \x01(\tR\x12rootPrivateKeyPath\"\x8d\t\n" +
	"\fClientConfig\x121\n" +
	"\x06server\x18\x01 \x01(\v2\x19.xray.common.net.EndpointR\x06server\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x06 \x01(\tR\n" +
	"deviceName\x12\x10\n" +
	"\x03sni\x18\a \x01(\tR\x03sni\x12\x19\n" +
	"\broot_pin\x18\b \x01(\tR\arootPin\x12)\n" +
	"\x10root_certificate\x18\t \x01(\tR\x0frootCertificate\x122\n" +
	"\x15root_certificate_path\x18\n" +
	" \x01(\tR\x13rootCertificatePath\x12-\n" +
	"\x12device_certificate\x18\v \x01(\tR\x11deviceCertificate\x126\n" +
	"\x17device_certificate_path\x18\f \x01(\tR\x15deviceCertificatePath\x12,\n" +
	"\x12device_private_key\x18\r \x01(\tR\x10devicePrivateKey\x125\n" +
	"\x17device_private_key_path\x18\x0e \x01(\tR\x14devicePrivateKeyPath\x12$\n" +
	"\x0ehop_port_count\x18\x0f \x01(\x05R\fhopPortCount\x123\n" +
	"\x15congestion_controller\x18\x10 \x01(\tR\x14congestionController\x12\x1b\n" +
	"\tquic_pool\x18\x11 \x01(\bR\bquicPool\x12)\n" +
	"\x11wait_for_open_ack\x18\x12 \x01(\bR\x0ewaitForOpenAck\x12&\n" +
	"\x0fudp_over_stream\x18\x13 \x01(\bR\rudpOverStream\x12,\n" +
	"\x12tcp_fallback_lanes\x18\x14 \x01(\x05R\x10tcpFallbackLanes\x12+\n" +
	"\x11handshake_timeout\x18\x15 \x01(\x05R\x10handshakeTimeout\x12*\n" +
	"\x11flow_idle_timeout\x18\x16 \x01(\x05R\x0fflowIdleTimeout\x12!\n" +
	"\fmax_sessions\x18\x17 \x01(\x05R\vmaxSessions\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x18 \x01(\x05R\tchunkSize\x12\x1c\n" +
	"\ttransport\x18\x19 \x01(\tR\ttransport\x12%\n" +
	"\x0efallback_delay\x18\x1a \x01(\x05R\rfallbackDelay\x12%\n" +
	"\x0efallback_grace\x18\x1b \x01(\x05R\rfallbackGrace\x12!\n" +
	"\fudp_cooldown\x18\x1c \x01(\x05R\vudpCooldown\x122\n" +
	"\x15udp_failure_threshold\x18\x1d \x01(\x05R\x13udpFailureThreshold\"\xd3\x04\n" +
	"\x0fTransportConfig\x12$\n" +
	"\x0ehop_port_count\x18\x01 \x01(\x05R\fhopPortCount\x12\x1e\n" +
	"\n" +
	"congestion\x18\x02 \x01(\tR\n" +
	"congestion\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\x12\x1b\n" +
	"\tquic_pool\x18\x04 \x01(\bR\bquicPool\x12)\n" +
	"\x11wait_for_open_ack\x18\x05 \x01(\bR\x0ewaitForOpenAck\x12&\n" +
	"\x0fudp_over_stream\x18\x06 \x01(\bR\rudpOverStream\x12+\n" +
	"\x11handshake_timeout\x18\a \x01(\x05R\x10handshakeTimeout\x12*\n" +
	"\x11flow_idle_timeout\x18\b \x01(\x05R\x0fflowIdleTimeout\x12!\n" +
	"\fmax_sessions\x18\t \x01(\x05R\vmaxSessions\x12,\n" +
	"\x12tcp_fallback_lanes\x18\n" +
	" \x01(\x05R\x10tcpFallbackLanes\x12\x1c\n" +
	"\ttransport\x18\v \x01(\tR\ttransport\x12%\n" +
	"\x0efallback_delay\x18\f \x01(\x05R\rfallbackDelay\x12%\n" +
	"\x0efallback_grace\x18\r \x01(\x05R\rfallbackGrace\x12!\n" +
	"\fudp_cooldown\x18\x0e \x01(\x05R\vudpCooldown\x122\n" +
	"\x15udp_failure_threshold\x18\x0f \x01(\x05R\x13udpFailureThresholdBX\n" +
	"\x16com.xray.proxy.queqiaoP\x01Z'github.com/xtls/xray-core/proxy/queqiao\xaa\x02\x12Xray.Proxy.Queqiaob\x06proto3"

var (
	file_proxy_queqiao_config_proto_rawDescOnce sync.Once
	file_proxy_queqiao_config_proto_rawDescData []byte
)

func file_proxy_queqiao_config_proto_rawDescGZIP() []byte {
	file_proxy_queqiao_config_proto_rawDescOnce.Do(func() {
		file_proxy_queqiao_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_queqiao_config_proto_rawDesc), len(file_proxy_queqiao_config_proto_rawDesc)))
	})
	return file_proxy_queqiao_config_proto_rawDescData
}

var file_proxy_queqiao_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proxy_queqiao_config_proto_goTypes = []any{
	(*Device)(nil),          // 0: xray.proxy.queqiao.Device
	(*Account)(nil),         // 1: xray.proxy.queqiao.Account
	(*ServerConfig)(nil),    // 2: xray.proxy.queqiao.ServerConfig
	(*ClientConfig)(nil),    // 3: xray.proxy.queqiao.ClientConfig
	(*TransportConfig)(nil), // 4: xray.proxy.queqiao.TransportConfig
	(*net.Endpoint)(nil),    // 5: xray.common.net.Endpoint
}
var file_proxy_queqiao_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.queqiao.Account.devices:type_name -> xray.proxy.queqiao.Device
	1, // 1: xray.proxy.queqiao.ServerConfig.accounts:type_name -> xray.proxy.queqiao.Account
	5, // 2: xray.proxy.queqiao.ClientConfig.server:type_name -> xray.common.net.Endpoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_queqiao_config_proto_init() }
func file_proxy_queqiao_config_proto_init() {
	if File_proxy_queqiao_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_queqiao_config_proto_rawDesc), len(file_proxy_queqiao_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_queqiao_config_proto_goTypes,
		DependencyIndexes: file_proxy_queqiao_config_proto_depIdxs,
		MessageInfos:      file_proxy_queqiao_config_proto_msgTypes,
	}.Build()
	File_proxy_queqiao_config_proto = out.File
	file_proxy_queqiao_config_proto_goTypes = nil
	file_proxy_queqiao_config_proto_depIdxs = nil
}
